### ISSUE TITLE
Live reload and https

### ISSUE THREAD

**Issue by jdann** [gimm/gulp-live-server#1]
Could you provide an example of how livereload is configured please as I can't get it to work for me.

I have the following to try and get an https application to use livereload but it fails as whatever i do the livereload option keeps getting overwritten by the default

var gls = require('gulp-live-server');

var livereload = {
  key: fs.readFileSync('./config/key.pem'),
  cert: fs.readFileSync('./config/cert.pem')
};

gulp.task('express', false, ['test'], function () {
  // Start the server at the beginning of the task
  var server = gls.new(paths.config + 'server.js');
  server.start();
});

**Comment by gimm** [comment]
@jdann I didn't know how to use `tiny-lr` in https, but I can tell you that, the way to set options for `tiny-lr` is using [gls](https://github.com/gimm/gulp-live-server/blob/master/README.md#glsargs-options-livereload).
For you case:

``` js
var server = gls([paths.config + 'server.js'], undefined, **livereload**);
```

livereload should be an object in your case.
I'd happy to know how to config tiny-lr in https if this works for you.

**Comment by jdann** [comment]
Thanks - changing var server = gls.new(paths.config + 'server.js'); to what you suggested fixed the issue. I had tried what you suggested but hadn't realized the first element (the server.js) should have been in an array.

Is it possible you could add an example on setting this info on your page?

**Comment by gimm** [comment]
@jdann will add more examples there for sure, but not now.
Thanks for your feedback.

**Comment by vennamo** [comment]
If the started server is inactive for a while, you get error message to console and the process stops. (yet the server is still open). Something to do with the live-reload..? (error points to connect)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at Function.app.listen (/node_modules/gulp-live-server/node_modules/connect/lib/proto.js:188:24)
    at Object.<anonymous> (/node_modules/gulp-live-server/scripts/static.js:16:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
