### ISSUE TITLE
server.start() doesn't return a promise once server has started

### ISSUE THREAD

**Issue by samhagman** [gimm/gulp-live-server#14]
From the code and from the behavior of calling server.start(), it looks like it only resolves if the server exits.

Maybe that was on purpose, but it seems that intuitively it would be called once the server has started successfully, not after the script file has run and then exited.

I would like to do something like this in my gulp file:

``` javascript
gulp.task('test-client', function (done) {

    var server = gls.new('server/index.js');

    server.start()
        .then(function () {
            karma.start({
                configFile: __dirname + '/spec/support/karma.conf.js',
                singleRun:  true
            }, function () {
                server.stop().then(done);
            });
        })
    ;

});
```

Where I can run my Karma tests once I know that the server has started successfully.

Would this be possible?

**Comment by gimm** [comment]
@sthagman sorry for the late reply, you should be able to add callback to `server.start`, check the tests for details https://github.com/gimm/gulp-live-server/blob/master/test/index.js

**Comment by niftylettuce** [comment]
@gimm Can you please document this better?

**Comment by lancedikson** [comment]
@gimm, did you mean the `notify` callback?

**Comment by gimm** [comment]
https://github.com/gimm/gulp-live-server/blob/master/test/index.js#L13
`server.start()` will return a promise

**Comment by lancedikson** [comment]
@gimm, but the promise will be resolved when the server exited: https://github.com/gimm/gulp-live-server/blob/master/index.js#L154

**Comment by gimm** [comment]
That's might because it doesn't exited as expected, namely `this.server.once('exit', function (code, sig)` didn't fire.
Sorry, I'm not sure about the exit codes or handle various exit situations.
Would be appreciate if you or anyone else can help here.
