### ISSUE TITLE
Custom content-type

### ISSUE THREAD

**Issue by Misiur** [gimm/gulp-live-server#16]
I'm having some problems with firefox and .sea files, as the server doesn't set content-type for any files. Is there a way to assign it manually? Is middleware required?

**Comment by gimm** [comment]
I assume you're using the default static server, this static server is powered by [serve-static](https://www.npmjs.com/package/serve-static), and it has a [setHeaders](https://www.npmjs.com/package/serve-static#setheaders) method. If that does not work for you, you can always use a custom server, like express, and use a middleware to handle your .sea file.
