### ISSUE TITLE
Cannot read property changed

### ISSUE THREAD

**Issue by mjancarik** [gimm/gulp-live-server#20]
Hi,

I have problem with new version live-server v0.0.17, which me return this Error.

```
/node_modules/gulp-live-server/index.js:194
        exports.lr.changed({body: {files: [filepath]}});
                  ^
TypeError: Cannot read property 'changed' of undefined
  at Object.exports.notify (/node_modules/gulp-live-server/index.js:194:19)
  at [object Object]._onTimeout (gulpfile.js:347:17)
  at Timer.listOnTimeout (timers.js:110:15)
```

Where would be a problem? I use v0.0.14 and there was everything ok.

Thanks

**Comment by brendannee** [comment]
I have the same issue.

**Comment by AlexeyGrishin** [comment]
+1

**Comment by shadowmint** [comment]
+1, just saw this as well.

**Comment by jmtsh** [comment]
+1 ... same here.

**Comment by shadowmint** [comment]
See the comments on https://github.com/gimm/gulp-live-server/commit/b0326e4aedfed3665051821c7df3e6ed61c703e1

Roll back the commit manually on your node_modules/gulp-live-server/index.js (it's two lines, you can do it by hand) to get this working again until it gets fixed in npm.

**Comment by mjancarik** [comment]
when it will be fix in npm?

**Comment by gimm** [comment]
fixed!
sorry for the delay.

**Comment by mjancarik** [comment]
v0.0.19 is all right..
