### ISSUE TITLE
error on sample page

### ISSUE THREAD

**Issue by meiriko** [gimm/gulp-live-server#36]
Hi

On your npm page you give a sample how to restart a server once the main js file changes:

```
gulp.watch('myapp.js', server.start.bind(server)); //restart my server 
```

This fails because the watch pipes the changed file to the start command.

What worked for me was:

```
gulp.watch('app.js', function(){server.start();}); //restart my server
```

**Comment by gimm** [comment]
thanks for your feedback, I'll try to update the document and plugin soon.

**Comment by ismyrnow** [comment]
I created a PR with this change. It uses `bind` when possible (`server.notify.bind(server)`) and an inline function when it's not (`server.start()`).

**Comment by ismyrnow** [comment]
Oops. Opened a PR on the wrong branch, initially. Should be ready for review and merging.
