### ISSUE TITLE
TypeError: Cannot read property 'lr' of null

### ISSUE THREAD

**Issue by nyakto** [gimm/gulp-live-server#38]
I trust there's error in [index.js](/gimm/gulp-live-server/blob/master/index.js) on line 207

``` javascript
   return es.map(function(file, done) {
       var filepath = path.relative(__dirname, file.path);
       debug(info('file(s) changed: %s'), filepath);
>>>    this.lr.changed({body: {files: [filepath]}});
       done(null, file);
   });
```

because no context will be given by `es.map`

this error breaks usage case:

``` javascript
gulp.src('')
    .pipe(server.notify());
```

**Comment by gimm** [comment]
why would you use an empty string '' here?

**Comment by nyakto** [comment]
It's just for the sample - assume there's a stream with some files
