### ISSUE TITLE
How to pass arguments from the command line to the 'app.js' file?

### ISSUE THREAD

**Issue by kiki-le-singe** [gimm/gulp-live-server#5]
example:

```
$ gulp server --env development

var gulp = require('gulp');
var gls = require('gulp-live-server');
var gutil = require('gulp-util');

console.log(gutil.env.env);

gulp.task('server', function () {
  var server = gls.new('server/app.js');
  server.start();
});
```

Thanks for your time

**Comment by gimm** [comment]
you need to use [gls](https://github.com/gimm/gulp-live-server#glsargs-options-livereload) if you want to pass cwd args to your app.js:

``` js
gulp.task('server', function() {
    var server = gls(['server.js', gutil.env.env]);
    server.start();
});
```

And in your `app.js`:
`process.argv` will be something like this `[ 'node',
  'full/path/to/your/app.js',
  'development' ]
`

`gls` uses `ChildProcess.spawn` underneath, so if you just want to set the node env, you should probably go with the 2nd param for gls: `options`
`

**Comment by kiki-le-singe** [comment]
It works :)
I didn't understand the use of [gls](https://github.com/gimm/gulp-live-server#glsargs-options-livereload), I tried to combine [new](https://github.com/gimm/gulp-live-server#newscript) with [gls](https://github.com/gimm/gulp-live-server#glsargs-options-livereload)
Thanks for your help

**Comment by gimm** [comment]
[static](https://github.com/gimm/gulp-live-server#staticfolder-port) and [new](https://github.com/gimm/gulp-live-server#newscript) are both use [gls](https://github.com/gimm/gulp-live-server#glsargs-options-livereload) internally, they're just short cuts for gls.

gls takes 3 params, 
- args
- options
- and the options for tiny-lr server

it spawn a child process using `ChildProcess.spawn` with `args` and `options`, so you can refer `ChildProcess.spawn` for details of `args` and `options`.
