### ISSUE TITLE
console.log colors not working

### ISSUE THREAD

**Issue by onemenzel** [gimm/gulp-live-server#57]
When using [chalk](https://www.npmjs.com/package/chalk) or [colors](https://www.npmjs.com/package/colors), it seems that the color gets stripped away by gulp-live-server. The terminal output will always be a black font.

**Comment by onemenzel** [comment]
solved by adding `stdio: 'inherit'` to gls parameters.

**Comment by leviwheatcroft** [comment]
I found this very helpful. It would be nice to include this in the README.md somewhere.
